### ISSUE TITLE
Jekyll Simple Layout

### ISSUE THREAD

**Issue by samrocksc** [samrocksc/awesome-phoenix#43]
Let's theme up some Jekyll!

**Comment by w33ble** [comment]
You don't like just having a readme anymore?

**Comment by samrocksc** [comment]
I'm just laying this out there if any prodigous soul wants to do it.  I may save it for someone at a coffee & code event that wants to learn how to make a website actually.

**Comment by samrocksc** [comment]
Ehhh, i am happy with the readme :P
